import type { SimEvent } from '../engine/events'
import type { Edge, Node } from '@xyflow/react'

/** Materials that are stored, carried by carts and consumed. Wounded men travel too, but are tracked apart. */
export const RESOURCES = ['viveri', 'acqua', 'foraggio', 'frecce', 'armi', 'legname'] as const
export type ResourceId = (typeof RESOURCES)[number]
export type Stock = Record<ResourceId, number>

export const BUILDING_KINDS = [
  'castello',
  'comando',
  'torre',
  'schieramento',
  'accampamento',
  'ospedale',
  'granaio',
  'deposito',
  'parcocarri',
  'villaggio',
  'pozzo',
  'fiume',
  'taglialegna',
  'frecciaio',
  'fucina',
] as const
export type BuildingKind = (typeof BUILDING_KINDS)[number]

export type Priority = 1 | 2 | 3
export type Fortification = 0 | 1 | 2 | 3

export interface BuildingData extends Record<string, unknown> {
  kind: BuildingKind
  name: string
  /** Men permanently posted to defend the building (they eat and drink too). */
  garrison: number
  /** Stock at the start of the simulation. */
  stock: Stock
  /** Storage capacity, tonnes (all resources together, by weight). */
  capacityT: number
  /** Output per turn (6 h) at full labour. Workshops also need their inputs, see RECIPES. */
  production: Stock
  fortification: Fortification
  /** Supply priority: 1 = served first. */
  priority: Priority
  /** Carts kept here: they join the army cart pool while the building is ours. */
  carts: number
  /** Hospital beds. */
  beds: number
  notes: string
}

export const TERRAINS = ['pianura', 'collina', 'altura', 'bosco', 'palude', 'fiume'] as const
export type Terrain = (typeof TERRAINS)[number]

export interface AreaData extends Record<string, unknown> {
  name: string
  terrain: Terrain
  /** Control at turn 0: +100 ours, -100 enemy. */
  control: number
  /** Area on the front line (scenarios aim here first). */
  front: boolean
  /** Generated by an exercise: position, size and terrain cannot be changed. */
  locked: boolean
  color: string
  notes: string
}

export const ROUTE_KINDS = ['strada', 'sterrato', 'sentiero', 'ponte', 'guado', 'fluviale'] as const
export type RouteKind = (typeof ROUTE_KINDS)[number]

export interface RouteData extends Record<string, unknown> {
  kind: RouteKind
  name: string
  /** null = measured on the map (see meta.logistics.kmPerPx). */
  lengthKm: number | null
  /** Carts that can enter the route per turn. null = default of the route kind. */
  capacity: number | null
  /** An escort patrols the route: ambushes are much less likely. */
  escort: boolean
  notes: string
}

export const UNIT_TYPES = ['fanteria', 'arcieri', 'balestrieri', 'cavalleria', 'genieri', 'milizia'] as const
export type UnitType = (typeof UNIT_TYPES)[number]

/**
 * fisso: holds its position, moves only on explicit orders.
 * mobile: follows orders.
 * riserva: follows orders and reinforces threatened areas on its own.
 */
export type Posture = 'fisso' | 'mobile' | 'riserva'

export interface UnitDef {
  id: string
  name: string
  type: UnitType
  men: number
  horses: number
  morale: number
  /** Building where the unit is stationed at turn 0. */
  nodeId: string | null
  posture: Posture
  /** Falls back on its own when morale collapses or the area is lost. */
  autoRetreat: boolean
  notes: string
}

export type EnemyBehavior = 'tieni' | 'avanza'

export interface EnemyForce {
  id: string
  name: string
  type: UnitType
  men: number
  /** Area where it is camped at turn 0. null = it appears directly on the target when the attack starts. */
  originAreaId: string | null
  /** Area it attacks. */
  targetAreaId: string | null
  behavior: EnemyBehavior
  /** Turn the attack starts. */
  startTurn: number
}

export interface LogisticsSettings {
  /** Kilograms carried by one cart. */
  cartCapacityKg: number
  /** Days of supplies each post tries to keep in stock. */
  targetDays: number
  /** Scale of the map: kilometres per canvas pixel. */
  kmPerPx: number
  /** Longest trip (hours) a convoy is sent on. */
  maxTripHours: number
}

export interface ProjectMeta {
  name: string
  description: string
  author: string
  revision: string
  createdAt: string
  updatedAt: string
  logistics: LogisticsSettings
  /** Guided walkthrough shown on the map (demos and exercises). */
  guide?: GuideStep[]
}

export interface GuideStep {
  title: string
  text: string
  /** Elements to select and frame with “Mostrami”. */
  focus?: string[]
  /** A change of situation the reader can trigger from the step. */
  action?: { label: string; event: SimEvent }
}

export type BuildingNode = Node<BuildingData, 'building'>
export type AreaNode = Node<AreaData, 'area'>
export type MapNode = BuildingNode | AreaNode
export type RouteEdge = Edge<RouteData, 'route'>

export const BUILDING_SIZE = { width: 196, height: 66 } as const
export const AREA_HEADER = 44
